export default {
    content: [
        "./index.html",
        "./src/**/*.{vue,js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', 'sans-serif'],
            },
            colors: {
                "on-secondary-fixed": "#00201d",
                "primary-container": "#131b2e",
                "inverse-primary": "#bec6e0",
                "inverse-surface": "#213145",
                "error": "#ba1a1a",
                "on-background": "#0b1c30",
                "primary-fixed": "#dae2fd",
                "error-container": "#ffdad6",
                "surface-dim": "#cbdbf5",
                "surface-bright": "#f8f9ff",
                "on-secondary-container": "#006f66",
                "surface-container-low": "#eff4ff",
                "surface-container-high": "#dce9ff",
                "secondary-fixed": "#89f5e7",
                "on-error-container": "#93000a",
                "surface": "#f8f9ff",
                "tertiary-fixed-dim": "#c0c1ff",
                "surface-container-lowest": "#ffffff",
                "background": "#f8f9ff",
                "on-tertiary": "#ffffff",
                "on-primary": "#ffffff",
                "surface-tint": "#565e74",
                "tertiary-container": "#07006c",
                "surface-container": "#e5eeff",
                "on-surface-variant": "#45464d",
                "on-primary-fixed": "#131b2e",
                "on-primary-fixed-variant": "#3f465c",
                "on-surface": "#0b1c30",
                "outline": "#76777d",
                "on-tertiary-fixed": "#07006c",
                "tertiary": "#000000",
                "on-error": "#ffffff",
                "tertiary-fixed": "#e1e0ff",
                "on-primary-container": "#7c839b",
                "primary-fixed-dim": "#bec6e0",
                "on-tertiary-fixed-variant": "#2f2ebe",
                "on-tertiary-container": "#7073ff",
                "surface-variant": "#d3e4fe",
                "primary": "#000000",
                "on-secondary": "#ffffff",
                "secondary": "#006a61",
                "inverse-on-surface": "#eaf1ff",
                "surface-container-highest": "#d3e4fe",
                "outline-variant": "#c6c6cd",
                "on-secondary-fixed-variant": "#005049",
                "secondary-container": "#86f2e4",
                "secondary-fixed-dim": "#6bd8cb"
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            spacing: {
                "lg": "24px",
                "sm": "8px",
                "margin": "24px",
                "xl": "32px",
                "xs": "4px",
                "unit": "4px",
                "md": "16px",
                "gutter": "16px"
            },
            fontSize: {
                "headline-xl": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "label-sm": ["11px", {"lineHeight": "14px", "letterSpacing": "0.03em", "fontWeight": "500"}],
                "headline-md": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                "body-sm": ["13px", {"lineHeight": "18px", "letterSpacing": "0", "fontWeight": "400"}],
                "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                "body-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0", "fontWeight": "400"}],
                "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600"}],
                "body-lg": ["16px", {"lineHeight": "24px", "letterSpacing": "0", "fontWeight": "400"}]
            }
        },
    },
    plugins: [
        require('@tailwindcss/typography'),
    ],
}
